version: "3.8"
services:
    birboard_server:
        image: "nginx:stable-alpine"
        ports:
            - 80:80
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - birdboard_api

    birdboard_api:
        build:
            context: ./dockerFiles
            dockerfile: birdboard_api.Dockerfile
        volumes:
            - ./birdboard:/var/www/birdboard